title: Skyler Wang

description: Actively Pursuing Electrical Engineering | Northeastern â€˜29 | 
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
just_the_docs:
  navigation_depth: 3
  logo: /Assets Github/Profile.png
