title: "Skyler Wang Portfolio"
description: "Engineering Portfolio and Projects"

# Must use remote_theme for GitHub Pages
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Sidebar / navigation order
just_the_docs:
  logo: "/assets/logo.png" # optional
  navigation_depth: 3
  show_download: false

# Optional: set homepage
defaults:
  - scope:
      path: ""
    values:
      layout: default
