title: "Skyler Wang Portfolio"
description: "Engineering Portfolio and Projects"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

just_the_docs:
  navigation_depth: 6
  show_download: true
